/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class antdlx_com_rsa_RSAHelper */

#ifndef _Included_antdlx_com_rsa_RSAHelper
#define _Included_antdlx_com_rsa_RSAHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     antdlx_com_rsa_RSAHelper
 * Method:    GetAPublicKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_antdlx_com_rsa_RSAHelper_GetAPublicKey
  (JNIEnv *, jobject);

/*
 * Class:     antdlx_com_rsa_RSAHelper
 * Method:    GetAPrivateKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_antdlx_com_rsa_RSAHelper_GetAPrivateKey
  (JNIEnv *, jobject);

/*
 * Class:     antdlx_com_rsa_RSAHelper
 * Method:    GetBPublicKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_antdlx_com_rsa_RSAHelper_GetBPublicKey
  (JNIEnv *, jobject);

/*
 * Class:     antdlx_com_rsa_RSAHelper
 * Method:    GetBPrivateKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_antdlx_com_rsa_RSAHelper_GetBPrivateKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
